### ISSUE TITLE
ECU Data Conversion

### ISSUE THREAD

**Issue by Squidtoon99** [DallasFormulaRacing/PowertrainLib#1]
Our ECU data is currently stored in PE3 CAN format and we need to decode + aggregate this data into a csv file.

This class should have 2 features:

1. Input a  CAN Message and output a dictionary of key value pairs with all metrics included in the message.

2. Input a CSV file with logs and output a formatted csv file with a "snapshot" of all metrics every 0.2 seconds.

**Comment by GHAFHA** [comment]
completed in labjackcanbus
