### ISSUE TITLE
Web Dashboard Design (+Figma)

### ISSUE THREAD

**Issue by Squidtoon99** [DallasFormulaRacing/PowertrainLib#13]
We need a cohesive UI design with proper components built to maintain consistency over various dashboard pages.

Tasks:
- [x] Create Figma Mockups for dashboard design
- [x] Create UI Guidelines for basic components and interactions 

Second Cycle:
- [x] Implement a track runs table which shows the driver, their time, and the difference from the time above it. The top of the table should have 3 buttons at the top labelled after different lengths (50m, 150m, 200m) this should sit in the bottom left and take up 1/3 of the screen.
- [x] Make the first graph (top left) take up 3/4 of the screen. It should have local maximums (peaks) have a ticker above that shows their value.
- [x] Make all graphs the agreed upon color.
- [x] Create a picture of the components using the black and orange theme from [shadcns color picker](https://ui.shadcn.com/themes)
- [x] Have the bottom middle graph be a historgram and take up 1/3 of the screen.
- [x] Include a highlights table in the top right that takes up 1/4 of the screen. This should include important metrics at a glance such as fastest lap, top RPM, and other values. (4-6)

**Comment by SahanYW** [comment]
Design references for color, layout, etc:
https://dribbble.com/shots/19514541-Activity-Tracking-Dashboard
https://dribbble.com/shots/16855795-Finance-Dashboard
https://dribbble.com/shots/19330110-Expenses-Tracking-Dashboard
https://dribbble.com/shots/15355572-CryptoQu-Cryptocurrency-Dashboard
https://dribbble.com/shots/21992874-Call-Analytics-Dashboard-Design
https://dribbble.com/shots/23053900-Sales-Marketing-Dashboard
https://dribbble.com/shots/23053900-Sales-Marketing-Dashboard

**Comment by Squidtoon99** [comment]
https://github.com/DallasFormulaRacing/PowertrainLib/assets/49101235/d72ddd13-3e85-45ad-8c83-79a38abce063

The home page for this dashboard is what I want to start out Figma design on.

**Comment by ThobesForBros** [comment]
![Dashboard](https://github.com/DallasFormulaRacing/PowertrainLib/assets/145950898/0dad60ae-c81e-420f-872c-7f994f317c78)


Currently what I have, still adding to it

**Comment by ThobesForBros** [comment]
![Home(1)](https://github.com/DallasFormulaRacing/PowertrainLib/assets/145950898/00ca82e6-74c7-4aad-a1b2-06a206c45698)


Using official DFR Colors, we can use different shades of orange for the graphs and use green for download buttons.

**Comment by ThobesForBros** [comment]
Two concepts I have for the Race Table, either it takes up the entire bottom half of the screen or it does 1/3. 

![Home(2)](https://github.com/DallasFormulaRacing/PowertrainLib/assets/145950898/6c863f0e-6bc6-4836-9864-eafe6498669b)
![Aero](https://github.com/DallasFormulaRacing/PowertrainLib/assets/145950898/80bdcd64-a5b1-4a70-88c1-eaef7e31c37a)

**Comment by Squidtoon99** [comment]
<img width="539" alt="image" src="https://github.com/DallasFormulaRacing/PowertrainLib/assets/49101235/6ddc40a0-ecb6-42aa-ad59-7e9f1b70997d">

**Comment by Squidtoon99** [comment]
Closed: Final Design Created
