### ISSUE TITLE
Telegraf Files

### ISSUE THREAD

**Issue by Squidtoon99** [DallasFormulaRacing/PowertrainLib#38]
Setting up Telegraf on the Raspberry PI for better metrics management and observability.

Tasks:

- [x] Setup UDP Input Plugin
- [x] Configure Telegraf to start on boot
- [x] CSV Output splitter based on session ID

**Comment by SahanYW** [comment]
Important links because I keep forgetting
pytelegraf: https://github.com/paksu/pytelegraf
input listener: https://github.com/influxdata/telegraf/blob/master/plugins/inputs/socket_listener/README.md
output csv: https://github.com/influxdata/telegraf/blob/master/plugins/outputs/execd/README.md
