### ISSUE TITLE
Graph Hosting Research

### ISSUE THREAD

**Issue by Squidtoon99** [DallasFormulaRacing/PowertrainLib#6]
Should be a small learning curve in the future. There are a few options 

These are a few ways that I know about.
- Grafana Cloud
- Datadog (also cloud)
- Hosted Jupyter Notebooks
- Generate images and send to discord via webhooks

Tasks:
- Research graphing solutions (ideally web based)
- Lots of flexibility
- I think that Hosted Jupyter Notebooks offer the best flexibility to the end-user but might require the most amount of work to setup and host.

**Comment by RochanVanam** [comment]
### **Options:**
1. Plotly/dash on github pages
**pros:** Very flexible, larger dashboard, easy to use, compatible with Mongo, _free tier_
**cons:** No video-graph sync, possible performance issues, bit harder to set up but not that bad

2. Google colab
**pros:** Easy to set up, easy to use, compatible with Mongo, _completely free_
**cons:** No video-graph sync

**Comment by Squidtoon99** [comment]
![image](https://github.com/DallasFormulaRacing/PowertrainLib/assets/49101235/f37586b8-08b0-4bd4-85a1-b9f3b0e0a5d3)

**Comment by Squidtoon99** [comment]
We have decided to go through with Plotly dash with specifics decided in the future.
