### ISSUE TITLE
AWS Cost Analysis + Database Research

### ISSUE THREAD

**Issue by Squidtoon99** [DallasFormulaRacing/PowertrainLib#7]
We don’t like spending money. Utilizing features like serverless and free tiers we can deploy most of our infrastructure for pennies.

Tasks:
- [x] Find AWS Database services and compare the cost for our usage 
- [x] Research free tiers from various cloud services to see which we can abuse
- [x] Find out how much data we are consuming and forecast how much we might need in the future.
- [x] Sample a test run and upload the data, use this to estimate how much data will be transferred over the span of a single testing session

**Comment by vasun123** [comment]
This shows how much storage we get in the free tier: https://aws.amazon.com/free/?all-free-tier.sort-by=item.additionalFields.SortRank&all-free-tier.sort-order=asc&awsf.Free%20Tier%20Types=*all&awsf.Free%20Tier%20Categories=*all

**Comment by vasun123** [comment]
output1_linpot_4.csv is the largest file (677 KB)
Time range is 733.9355659484863 seconds
677 / 733.9355659484863 = 0.92242429909 KB/sec
0.92242429909 x 60 x 60 x 3 = 9962.18243017 KB = 9.962182430169999 MB in 3 hours
9.96218243022 x 1.25(for 25% margin) = 12.4527280378 MB

Accelerometer:
File size is 30.5 KB
Time range is 36.63216543197632 seconds
30.5 / 36.63216543197632 = 0.83260161228 KB/sec
0.83260161228 x 60 x 60 x 3 = 8992.09741262 KB = 8.99209741262 MB in 3 hours
8.99209741262 x 1.25(for 25% margin) = 11.2401217658 MB

ECU:
File size is 6 MB (according to Discord)
Time range is 99.996 seconds
6 / 99.996 = 0.06000240009 MB/sec
0.06000240009 x 60 x 60 x 3 = 648.025920972 MB in 3 hours
648.025920972 x 1.25(for 25% margin) = 810.032401215 MB

12.4527280378 + 11.2401217658 + 810.032401215 = 833.725251019 MB = 0.833725251019 GB

**Comment by Squidtoon99** [comment]
I will convey this information to the business team. Thank you
